### ISSUE TITLE
Question: Ordering the returned rows like in the UI

### ISSUE THREAD

**Issue by tomerbsentinel** [getredash/redash-toolbelt#119]
Hi,

When performing the file mentioned here: https://github.com/getredash/redash-toolbelt/blob/master/redash_toolbelt/examples/refresh_query.py

I am getting all the needed rows, but I do need to work on it more to sort them as I see in the UI.

My question is, is there is a possibility to get those results already sorted as I see in the UI?

![image](https://user-images.githubusercontent.com/38854357/145437547-47b4ca61-a355-483d-9e3f-680bb5d3d994.png)

And in the Python script, this is what I'm getting (unsorted like my initial query) :
![image](https://user-images.githubusercontent.com/38854357/145437889-df3116a2-2430-4616-9390-d04dfbe37fe0.png)

Thanks for helping me out.

**Comment by tomerbsentinel** [comment]
ok,

I did it with Pandas.

    results, return_columns = get_fresh_query_result(redash_url, query_id, api_key,
                               params)
    df = pd.DataFrame(results, columns=[x['friendly_name'] for x in
                                        return_columns])
    print(df.to_html())

**Comment by susodapop** [comment]
Sorting is handled by the query. The sort order returned by the results API is the same order rows were returned by your query. You can either modify the query to return the sort order you prefer, or you can sort it after-the-fact like you did with Pandas.
