### ISSUE TITLE
Refresh API with date range parameter

### ISSUE THREAD

**Issue by hwy1782** [getredash/redash-toolbelt#32]
If I try get data by date range parameters like below:

https://xxx/queries/238/source?p_train_id=xxx&p_depature_date.start=2020-07-01&p_depature_date.end=2020-07-02

i use  `get_fresh_query_result(redash_url, query_id, api_key, params)` api and build params like that :
```
params = {'p_train_id': 'xxx',
              'p_depature_date.start': '2020-07-01',
              'p_depature_date.end': '2020-07-02'}
```

but it can not work , i see the request detail it's that:
```
SELECT *
FROM train_time_table
WHERE train_id = 'xxx'
  AND depature_date >= ''
  AND depature_date <= ''
ORDER BY start_time DESC
```

how can i build the request params for date range parameters

**Comment by susodapop** [comment]
Date range parameters in the Redash API look like so:

```
{
	"date-range-parameter": {
		"start": "2020-01-1",
		"end": "2020-01-31"
	}
}
```

Refreshing a query should use the `/results` endpoint which is documented [here](https://redash.io/help/user-guide/integrations-and-api/api).

Note: this repo isn't the place for this kind of question. Please post to [the forum](discuss.redash.io) instead. Thanks!

**Comment by hwy1782** [comment]
thanks
