### ISSUE TITLE
Migration Script: convert origin QRDS queries to destination

### ISSUE THREAD

**Issue by susodapop** [getredash/redash-toolbelt#64]
## Description

This issue only applies after #23 merges. When the migration moves objects from an origin instance to a destination instance, the object ID's are reset. For example `<Query 45321>` in the origin might be `<Query 6>` in the destination. But queries using the QRDS data source depend on the query ID's not changing.

I propose an additional step in the migration script that examines the text of QRDS queries and substitutes the correct query_id.

```sql
-- Before
SELECT * FROM query_45321

-- After
SELECT * FROM query_6
```

**Comment by susodapop** [comment]
This should be straightforward to implement. If a member of the community would like to pick it up I'm happy to assist.

**Comment by mvsleak** [comment]
Hi, what would be a nice way to do this?
