### ISSUE TITLE
redash-migrate: command not found

### ISSUE THREAD

**Issue by nswbmw** [getredash/redash-toolbelt#84]
$ uname -a
Linux redash 4.15.0-158-generic #166-Ubuntu SMP Fri Sep 17 19:37:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ pip install --upgrade redash-toolbelt
Requirement already up-to-date: redash-toolbelt in /usr/local/lib/python3.6/dist-packages
Requirement already up-to-date: requests<3.0.0,>=2.22.0 in /usr/local/lib/python3.6/dist-packages (from redash-toolbelt)
Requirement already up-to-date: click<8.0,>=7.0 in /usr/local/lib/python3.6/dist-packages (from redash-toolbelt)
Requirement already up-to-date: charset-normalizer~=2.0.0; python_version >= "3" in /usr/local/lib/python3.6/dist-packages (from requests<3.0.0,>=2.22.0->redash-toolbelt)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests<3.0.0,>=2.22.0->redash-toolbelt)
Requirement already up-to-date: idna<4,>=2.5; python_version >= "3" in /usr/local/lib/python3.6/dist-packages (from requests<3.0.0,>=2.22.0->redash-toolbelt)
Requirement already up-to-date: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests<3.0.0,>=2.22.0->redash-toolbelt

$ redash-migrate  --version
redash-migrate: command not found

**Comment by susodapop** [comment]
Hi `nswbmw` does your `pip` point to the pything packaging index? Or are you using a mirror? The latest released version of redash-toolbelt is 0.1.6. The migration script was introduced in 0.1.5.

`pip install --upgrade redash-toolbelt` ought to install the latest version available at PyPi. I'm not able to reproduce a case where this doesn't work. Which makes me think your machine might be aimed at a different index.

Worst case you can bypass Pypi completely and install it this way.

1. Download the latest release from our [releases](https://github.com/getredash/redash-toolbelt/releases) page. You'll just need the `.tar.gz` file.
2. Install this file in your Python environment like this: `pip install <path_to_tar.gz_file>`
